export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';
export const RESET_ITEMS = 'RESET_ITEMS';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const FETCH_ORDER_REQUEST = 'SUBMIT_ORDER_REQUEST';
export const FETCH_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'SUBMIT_ORDER_FAILURE';
export const RESET_ORDER_STATE = 'RESET_ORDER_STATE';